import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export function generateTokensCss(): string {
  const rootDir = path.resolve(__dirname, '../../../');
  const tokensDir = path.join(rootDir, 'packages/design-tokens/tokens');

  const colors = JSON.parse(fs.readFileSync(path.join(tokensDir, 'colors.json'), 'utf8'));
  const typography = JSON.parse(fs.readFileSync(path.join(tokensDir, 'typography.json'), 'utf8'));
  const spacing = JSON.parse(fs.readFileSync(path.join(tokensDir, 'spacing.json'), 'utf8'));
  const radii = JSON.parse(fs.readFileSync(path.join(tokensDir, 'radii.json'), 'utf8'));
  const shadows = JSON.parse(fs.readFileSync(path.join(tokensDir, 'shadows.json'), 'utf8'));
  const targets = JSON.parse(fs.readFileSync(path.join(tokensDir, 'targets.json'), 'utf8'));

  const lines = [
    '/*',
    ' * GENERATED FILE - DO NOT EDIT MANUALLY',
    ' * Generated by tools/codegen from packages/design-tokens/tokens/*.json',
    ' * KrishiSetu Design Tokens (UX4G/GIGW-aligned design baseline)',
    ' */',
    '',
    ':root {',
    '  color-scheme: light;',
    '',
    `  --ks-font-latin: ${typography.fonts.latin};`,
    `  --ks-font-devanagari: ${typography.fonts.devanagari};`,
    `  --ks-font-kannada: ${typography.fonts.kannada};`,
    '',
    `  --ks-color-civic-blue: ${colors['civic-blue']};`,
    `  --ks-color-civic-blue-dark: ${colors['civic-blue-dark']};`,
    `  --ks-color-civic-blue-light: ${colors['civic-blue-light']};`,
    `  --ks-color-agri-green: ${colors['agri-green']};`,
    `  --ks-color-agri-green-dark: ${colors['agri-green-dark']};`,
    `  --ks-color-surface-page: ${colors['surface-page']};`,
    `  --ks-color-surface-card: ${colors['surface-card']};`,
    `  --ks-color-text: ${colors['text']};`,
    `  --ks-color-text-muted: ${colors['text-muted']};`,
    `  --ks-color-border: ${colors['border']};`,
    `  --ks-color-error: ${colors['error']};`,
    `  --ks-color-error-dark: ${colors['error-dark']};`,
    `  --ks-color-error-surface: ${colors['error-surface']};`,
    `  --ks-color-success: ${colors['success']};`,
    `  --ks-color-success-dark: ${colors['success-dark']};`,
    `  --ks-color-success-surface: ${colors['success-surface']};`,
    `  --ks-color-warning-surface: ${colors['warning-surface']};`,
    `  --ks-color-warning-text: ${colors['warning-text']};`,
    `  --ks-color-focus: ${colors['focus']};`,
    '',
    `  --ks-font-size-xs: ${typography.sizes.xs};`,
    `  --ks-font-size-sm: ${typography.sizes.sm};`,
    `  --ks-font-size-md: ${typography.sizes.md};`,
    `  --ks-font-size-lg: ${typography.sizes.lg};`,
    `  --ks-font-size-xl: ${typography.sizes.xl};`,
    `  --ks-font-size-2xl: ${typography.sizes['2xl']};`,
    '',
    `  --ks-line-height-xs: ${typography.lineHeights.xs};`,
    `  --ks-line-height-sm: ${typography.lineHeights.sm};`,
    `  --ks-line-height-md: ${typography.lineHeights.md};`,
    `  --ks-line-height-lg: ${typography.lineHeights.lg};`,
    `  --ks-line-height-xl: ${typography.lineHeights.xl};`,
    `  --ks-line-height-2xl: ${typography.lineHeights['2xl']};`,
    '',
    `  --ks-font-weight-regular: ${typography.weights.regular};`,
    `  --ks-font-weight-semibold: ${typography.weights.semibold};`,
    `  --ks-font-weight-bold: ${typography.weights.bold};`,
    '',
    `  --ks-space-1: ${spacing['1']};`,
    `  --ks-space-2: ${spacing['2']};`,
    `  --ks-space-3: ${spacing['3']};`,
    `  --ks-space-4: ${spacing['4']};`,
    `  --ks-space-5: ${spacing['5']};`,
    `  --ks-space-6: ${spacing['6']};`,
    `  --ks-space-8: ${spacing['8']};`,
    `  --ks-space-10: ${spacing['10']};`,
    `  --ks-space-12: ${spacing['12']};`,
    '',
    `  --ks-radius-sm: ${radii.sm};`,
    `  --ks-radius-md: ${radii.md};`,
    `  --ks-radius-lg: ${radii.lg};`,
    '',
    '  --ks-border-width: 1px;',
    '  --ks-border-width-strong: 2px;',
    `  --ks-touch-min: ${targets.touchMin};`,
    `  --ks-touch-comfortable: ${targets.touchComfortable};`,
    `  --ks-control-height: ${targets.controlHeight};`,
    `  --ks-content-max: ${targets.contentMax};`,
    `  --ks-shadow-card: ${shadows.card};`,
    '  --ks-focus-outline: 3px solid var(--ks-color-focus);',
    '  --ks-focus-offset: 3px;',
    '}',
    '',
    '*, *::before, *::after {',
    '  box-sizing: border-box;',
    '}',
    '',
    'html {',
    '  font-family: var(--ks-font-latin);',
    '  font-size: 100%;',
    '  line-height: 1.5;',
    '  text-size-adjust: 100%;',
    '}',
    '',
    'html:lang(mr), html:lang(hi), html:lang(sa), :lang(mr), :lang(hi), :lang(sa), :lang(mr-Deva), :lang(hi-Deva), :lang(sa-Deva) {',
    '  font-family: var(--ks-font-devanagari);',
    '}',
    '',
    'html:lang(kn), :lang(kn), :lang(kn-Knda) {',
    '  font-family: var(--ks-font-kannada);',
    '}',
    '',
    'body {',
    '  margin: 0;',
    '  color: var(--ks-color-text);',
    '  background: var(--ks-color-surface-page);',
    '  font-size: var(--ks-font-size-md);',
    '  line-height: var(--ks-line-height-md);',
    '}',
    '',
    '@media (prefers-reduced-motion: reduce) {',
    '  *, *::before, *::after {',
    '    scroll-behavior: auto !important;',
    '    animation-duration: 0.01ms !important;',
    '    animation-iteration-count: 1 !important;',
    '    transition-duration: 0.01ms !important;',
    '  }',
    '}',
  ];

  return lines.join('\n');
}

export function writeGeneratedTokens(): void {
  const rootDir = path.resolve(__dirname, '../../../');
  const targetDir = path.join(rootDir, 'packages/design-tokens/generated');
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }
  const css = generateTokensCss();
  fs.writeFileSync(path.join(targetDir, 'krishisetu.tokens.css'), css, 'utf8');
}
