import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function extractKeys(obj: Record<string, unknown>, prefix = ''): string[] {
  const keys: string[] = [];
  for (const [k, v] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${k}` : k;
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      keys.push(...extractKeys(v as Record<string, unknown>, fullKey));
    } else {
      keys.push(fullKey);
    }
  }
  return keys;
}

export function generateMessageKeys(): string {
  const rootDir = path.resolve(__dirname, '../../../');
  const enDir = path.join(rootDir, 'packages/i18n/messages/en');

  const files = fs.readdirSync(enDir).filter((f) => f.endsWith('.json'));
  const allKeys: string[] = [];

  for (const file of files) {
    const namespace = file.replace('.json', '');
    const content = JSON.parse(fs.readFileSync(path.join(enDir, file), 'utf8'));
    allKeys.push(...extractKeys(content, namespace));
  }

  allKeys.sort();

  const code = `/* ==========================================================================
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by tools/codegen from packages/i18n/messages/en/*.json
 * KrishiSetu Typed Message Keys
 * ========================================================================== */

export const ALL_MESSAGE_KEYS = [
${allKeys.map((k) => `  '${k}',`).join('\n')}
] as const;

export type MessageKey = (typeof ALL_MESSAGE_KEYS)[number];
`;

  return code;
}

export function writeGeneratedMessageKeys(): void {
  const rootDir = path.resolve(__dirname, '../../../');
  const targetDir = path.join(rootDir, 'packages/i18n/src/generated');
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }
  const code = generateMessageKeys();
  fs.writeFileSync(path.join(targetDir, 'message-keys.ts'), code, 'utf8');
}
