FROM node:22.17.0-alpine
WORKDIR /app
ARG API_BASE_URL=http://api:3001
ENV NEXT_PUBLIC_API_BASE_URL=${API_BASE_URL}
COPY . .
RUN npm ci --ignore-scripts && npm run codegen && npm run build -w apps/web
EXPOSE 3000
CMD ["npm", "run", "start", "-w", "apps/web"]
