import type { PublicHomeViewModel } from './public-home.types.js';

export const PUBLIC_HOME_FIXTURE: PublicHomeViewModel = {
  provenance: {
    mode: 'SYNTHETIC',
    updatedAt: '2026-08-27T03:30:00.000Z',
    displayUpdatedAt: '27 August 2026, 9:00 AM IST',
    labelKey: 'publicHome.common.syntheticDataLabel',
  },
  widgetStates: {
    alert: 'AVAILABLE',
    weather: 'AVAILABLE',
    market: 'AVAILABLE',
    advisory: 'AVAILABLE',
    schemes: 'AVAILABLE',
    notices: 'AVAILABLE',
    updates: 'AVAILABLE',
  },
  alert: {
    noticeId: 'notice-2026-002',
    labelKey: 'publicHome.alert.label',
    titleKey: 'publicHome.alert.title',
    fallbackTitle: 'Solar pump subsidy applications close on 31 August 2026',
    metaKey: 'publicHome.alert.meta',
    fallbackMeta: 'Synthetic demo notice • Updated 27 August 2026',
    actionKey: 'publicHome.alert.viewNotice',
  },
  weather: {
    districtId: 'pune',
    districtLabel: 'Pune',
    talukaLabel: 'Haveli',
    temperatureCelsius: 27,
    condition: 'Moderate rain',
    conditionCode: 'MODERATE_RAIN',
    rainfallProbabilityPercent: 68,
    rainfallMm24h: 14.2,
    relativeHumidityPercent: 82,
    windSpeedKmh: 18.5,
    warning: 'Yellow rainfall watch',
    sourceLabel: 'Mock Agromet adapter',
    prototypeData: true,
  },
  advisory: {
    title: 'Pause spraying during rain and inspect low-lying plots',
    summary:
      'Delay foliar spraying until a dry window. Check soybean and pigeon-pea plots for standing water and clear blocked drainage channels.',
    validity: 'Valid through 31 August 2026',
    source: 'Synthetic agromet advisory',
    prototypeData: true,
  },
  marketRows: [
    {
      commodity: 'Soybean',
      commodityKey: 'publicHome.market.commoditySoybean',
      modalPricePaise: 465000,
      displayPrice: '₹4,650/q',
      changePercent: 1.8,
      direction: 'UP',
      arrivalQuintals: 124,
    },
    {
      commodity: 'Onion',
      commodityKey: 'publicHome.market.commodityOnion',
      modalPricePaise: 225000,
      displayPrice: '₹2,250/q',
      changePercent: -2.3,
      direction: 'DOWN',
      arrivalQuintals: 340,
    },
    {
      commodity: 'Tomato',
      commodityKey: 'publicHome.market.commodityTomato',
      modalPricePaise: 180000,
      displayPrice: '₹1,800/q',
      changePercent: 4.2,
      direction: 'UP',
      arrivalQuintals: 95,
    },
    {
      commodity: 'Pigeon pea',
      commodityKey: 'publicHome.market.commodityPigeonPea',
      modalPricePaise: 745000,
      displayPrice: '₹7,450/q',
      changePercent: 0.7,
      direction: 'UP',
      arrivalQuintals: 76,
    },
  ],
  featuredSchemes: [
    {
      schemeId: 'offering_drip_2026',
      schemeCode: 'MAHADBT_DRIP',
      titleKey: 'publicHome.schemes.dripTitle',
      fallbackTitle: 'PMKSY - Drip Irrigation Subsidy Scheme',
      benefitKey: 'publicHome.schemes.dripBenefit',
      fallbackBenefit: 'Up to 80% synthetic subsidy illustration',
      audienceKey: 'publicHome.schemes.dripAudience',
      fallbackAudience: 'Small and marginal farmers',
      stateKey: 'publicHome.schemes.dripStatus',
      fallbackState: 'Open until 30 September 2026',
      returnToPath: '/schemes/MAHADBT_DRIP',
      prototypeData: true,
    },
    {
      schemeId: 'offering_rotavator_2026',
      schemeCode: 'SMAM_ROTAVATOR',
      titleKey: 'publicHome.schemes.rotavatorTitle',
      fallbackTitle: 'SMAM - Farm Machinery & Rotavator Subsidy',
      benefitKey: 'publicHome.schemes.rotavatorBenefit',
      fallbackBenefit: 'Up to 50% synthetic subsidy illustration',
      audienceKey: 'publicHome.schemes.rotavatorAudience',
      fallbackAudience: 'Farmers seeking machinery support',
      stateKey: 'publicHome.schemes.rotavatorStatus',
      fallbackState: 'Open',
      returnToPath: '/schemes/SMAM_ROTAVATOR',
      prototypeData: true,
    },
    {
      schemeId: 'offering_kcc_2026',
      schemeCode: 'KCC_CROP_LOAN',
      titleKey: 'publicHome.schemes.kccTitle',
      fallbackTitle: 'Kisan Credit Card (KCC) Crop Loan',
      benefitKey: 'publicHome.schemes.kccBenefit',
      fallbackBenefit: 'Synthetic crop-credit illustration',
      audienceKey: 'publicHome.schemes.kccAudience',
      fallbackAudience: 'Eligible cultivators after consent-based checks',
      stateKey: 'publicHome.schemes.kccStatus',
      fallbackState: 'Available for eligibility check',
      returnToPath: '/schemes',
      prototypeData: true,
    },
  ],
  notices: [
    {
      id: 'notice-2026-002',
      priority: 'CRITICAL',
      date: '25 August 2026',
      dateKey: 'publicHome.noticesAndUpdates.notice1Date',
      titleKey: 'notifications.notices.solarDeadline.title',
      fallbackTitle: 'Solar pump subsidy applications close on 31 August 2026',
      summaryKey: 'notifications.notices.solarDeadline.summary',
      fallbackSummary:
        'Final reminder for small and marginal farmers in Pune district to submit online documentation for solar water pumps.',
      source: 'MahaDBT Schemes Adapter',
      prototypeData: true,
    },
    {
      id: 'notice-2026-001',
      priority: 'HIGH',
      date: '1 August 2026',
      dateKey: 'publicHome.noticesAndUpdates.notice2Date',
      titleKey: 'notifications.notices.dripWindow.title',
      fallbackTitle: 'PMKSY micro-irrigation subsidy window open for Kharif 2026',
      summaryKey: 'notifications.notices.dripWindow.summary',
      fallbackSummary:
        'Applications invited for drip and sprinkler irrigation installations. Subsidy up to 80% for eligible holdings.',
      source: 'MahaDBT Schemes Adapter',
      prototypeData: true,
    },
    {
      id: 'notice-2026-003',
      priority: 'NORMAL',
      date: '10 August 2026',
      dateKey: 'publicHome.noticesAndUpdates.notice3Date',
      titleKey: 'notifications.notices.revisedForm.title',
      fallbackTitle: 'Revised self-declaration form v3.1 released for agricultural subsidies',
      summaryKey: 'notifications.notices.revisedForm.summary',
      fallbackSummary:
        'Updated self-declaration template simplifies land verification and eliminates physical stamp paper requirements.',
      source: 'Agriculture Department',
      prototypeData: true,
    },
  ],
  updates: [
    {
      id: 'update-2026-001',
      titleKey: 'publicHome.noticesAndUpdates.update1Title',
      fallbackTitle: 'Preparing soybean fields after heavy rainfall',
      dateKey: 'publicHome.noticesAndUpdates.update1Date',
      fallbackDate: '24 August 2026',
      categoryKey: 'publicHome.noticesAndUpdates.categorySeasonal',
      fallbackCategory: 'Seasonal guidance',
      summaryKey: 'publicHome.noticesAndUpdates.update1Summary',
      fallbackSummary: 'Simple drainage and field-inspection steps to reduce waterlogging risk.',
      source: 'Synthetic editorial content',
      prototypeData: true,
    },
    {
      id: 'update-2026-002',
      titleKey: 'publicHome.noticesAndUpdates.update2Title',
      fallbackTitle: 'Five questions to ask before choosing a mandi',
      dateKey: 'publicHome.noticesAndUpdates.update2Date',
      fallbackDate: '23 August 2026',
      categoryKey: 'publicHome.noticesAndUpdates.categoryMarket',
      fallbackCategory: 'Market readiness',
      summaryKey: 'publicHome.noticesAndUpdates.update2Summary',
      fallbackSummary:
        'Compare modal price, transport cost, arrivals, quality rules and payment timing.',
      source: 'Synthetic editorial content',
      prototypeData: true,
    },
    {
      id: 'update-2026-003',
      titleKey: 'publicHome.noticesAndUpdates.update3Title',
      fallbackTitle: 'How farmer producer organisations can improve market access',
      dateKey: 'publicHome.noticesAndUpdates.update3Date',
      fallbackDate: '21 August 2026',
      categoryKey: 'publicHome.noticesAndUpdates.categoryCollectives',
      fallbackCategory: 'Farmer collectives',
      summaryKey: 'publicHome.noticesAndUpdates.update3Summary',
      fallbackSummary:
        'A short introduction to aggregation, negotiation and shared logistics.',
      source: 'Synthetic editorial content',
      prototypeData: true,
    },
  ],
};
